---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  labels:
    app: "hello"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    helm.sh/release: "{{ .Release.Name }}"
    helm.sh/revision: "{{ .Release.Revision }}"
spec:
  maxReplicas: {{ .Values.horizontalPodAutoscaler.maxReplicas }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Release.Name }}
  targetCPUUtilizationPercentage: {{ .Values.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
...