---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-anyuid
  labels:
    app: "hello"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    helm.sh/release: "{{ .Release.Name }}"
    helm.sh/revision: "{{ .Release.Revision }}"
...